
FROM python:3.9

ADD ./back-end/requirements.txt /tmp/requirements.txt




RUN pip install --no-cache-dir --upgrade -r /tmp/requirements.txt

COPY ./back-end /back-end

ENV PYTHONPATH "${PYTHONPATH}:/back-end/"

CMD ["uvicorn", "back-end.api:app", "--host", "0.0.0.0", "--port", "8000"]