
# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM node:lts-alpine3.10 as build-stage

# RUN apk add --no-cache git
# RUN git --version

ADD ./package.json /meraki-explorer/
ADD ./public /meraki-explorer/public
ADD ./src /meraki-explorer/src

WORKDIR /meraki-explorer

RUN npm install && \
    npm run build


# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.16.0-alpine


# COPY build /usr/share/nginx/meraki-explorer/build

COPY --from=build-stage /meraki-explorer/build/ /usr/share/nginx/meraki-explorer/build


# Copy the default nginx default.conf 

COPY dockersmeraki-explorer/ngnix/default.conf /etc/nginx/conf.d/default.conf