
FROM python:3.9

ADD ./back-end/requirements.txt /tmp/requirements.txt




RUN pip install --no-cache-dir --upgrade -r /tmp/requirements.txt

COPY ./back-end /back-end


ENV PYTHONPATH "${PYTHONPATH}:/back-end/"

#start FastApi
CMD ["pytest", "-v"]