version: "3"
services:
  fastapi:
    build:
      context: ../
      dockerfile: dockersmeraki-explorer/Dockerfile_fastapi
    container_name: meraki-explorer-fastapi
    hostname: fastapi
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - MONGODB_URL=$MONGODB_URL_PROD
      - "TZ=Europe/Vienna"
    volumes:
      - log-data:/back-end
    restart: always
    stop_grace_period: 120s

  ngnix:
    build:
      context: ../
      dockerfile: dockersmeraki-explorer/Dockerfile_ngnix

    container_name: meraki-explorer-ngnix
    hostname: ngnix
    environment:
      - "TZ=Europe/Vienna"
    restart: on-failure
    ports:
      - 81:80
    depends_on:
      - fastapi

  mongodb:
    image: mongo:5.0.7
    container_name: meraki-explorer-mongodb
    hostname: mongodb
    env_file:
      - ./.env
    ports:
      - 27018:27017
    restart: on-failure
    stop_grace_period: 120s
    volumes:
      - meraki-explorer-mongo-data:/data/db

volumes:
  meraki-explorer-mongo-data:
    driver: local
  log-data:
    driver: local
