
FROM python:3.9

ADD ./websocket/requirements.txt /tmp/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /tmp/requirements.txt



COPY ./websocket /websocket

ENV PYTHONPATH "${PYTHONPATH}:/websocket/"


#start websocket server
CMD ["gunicorn"  , "-b", "0.0.0.0:5000", "websocket.websocketserver:app","--log-level","debug", "--timeout", "900"]

