version: "3"
services:
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile_fastapi
    container_name: meraki-explorer-fastapi
    hostname: fastapi
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    environment:
      - "TZ=Europe/Vienna"
    volumes:
      - log-data:/log
    restart: on-failure
    stop_grace_period: 120s

  mongodb:
    image: mongo:5.0.7
    container_name: meraki-explorer-mongodb
    hostname: mongodb
    ports:
      - 27018:27017
    restart: on-failure
    stop_grace_period: 120s
    volumes:
      - meraki-explorer-mongo-data:/data/db

volumes:
  meraki-explorer-mongo-data:
    driver: local
  log-data:
    driver: local
