name: lint
on: [push, pull_request]
jobs:
  tox-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: tox -e lint

  tox-docs-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: tox -e docs-lint

  tox-pycodestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: tox -e pycodestyle
