# .github/workflows/app.yaml
name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: MERAKI_DEMO_API_KEY

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build fastapi app
        working-directory: ./back-end
        run: docker-compose build --no-cache fastapi && docker-compose up -d fastapi

      # # Setup Python (faster than using Python container)
      # - name: Setup Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.10.4"

      # - name: Install pipenv
      #   run: |
      #     python -m pip install --upgrade pipenv wheel
      # - id: cache-pipenv
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.local/share/virtualenvs
      #     key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      # - name: Install dependencies
      #   if: steps.cache-pipenv.outputs.cache-hit != 'true'
      #   run: |
      #     pipenv install --deploy --dev
      # - name: Run test suite
      #   run: |
      #     pipenv run test -v
