name: Read File

on: [push, pull_request]

jobs:
  read_file:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: pwd
        run: pwd
      - uses: addnab/docker-run-action@v3
        with:
          registry: gcr.io
          image: cyberfrollo/pytest
          options: -v ${{ github.workspace }}:/test
          run: |
            ls -al
